# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
  example-workflow:
    jobs:
      - cypress/run:
          wait-on: http://localhost:19006
          start: npm run web
